common:
  data_root: data/MouseSIS
  iou_threshold: 0.1
  split: test
  sequence_ids: [1, 7, 10, 16, 22, 26, 28, 32]

gray_detector:
  yolo_path: ./models/yolo_frame.pt

e2vid_detector:
  yolo_path: /home/coraldl/EV/MouseSIS/scripts/runs/fine_tune/yolo11n_1280x720/weights/best.pt

tracker:
  max_age: 1
  min_hits: 3
  iou_threshold: 0.3

output_dir: ./output/
