common:
  data_root: data
  iou_threshold: 0.1
  split: val_kl
  sequence_ids: [3, 4, 12, 25]

gray_detector:
  yolo_path: ./models/yolo_frame.pt

e2vid_detector:
  yolo_path: /scripts/runs/fine_tune/yolo11n_1280x720/weights/best.pt

tracker:
  max_age: 1
  min_hits: 3
  iou_threshold: 0.3

output_dir: ./output/
