common:
  data_root: data
  iou_threshold: 0.1
  split: test_ave
  sequence_ids: [10, 16, 22, 26, 28, 32]

e2vid_detector:
  yolo_path: /scripts/runs/fine_tune/yolo11n_ave/weights/best.pt

tracker:
  max_age: 1
  min_hits: 3
  iou_threshold: 0.3

output_dir: ./output/
